[book]
title = "Modern Java"
description = " Book teaching how to write modern and effective Java. It is maintained by the community, anyone can contribute."
authors = ["Together Java", "Contributions from the Java Community"]
language = "en"
multilingual = false

[output.html]
git-repository-url = "https://github.com/Together-Java/ModernJava"
edit-url-template = "https://github.com/Together-Java/ModernJava/edit/develop/{path}"
mathjax-support = true

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[preprocessor.features]
command = "python3 features.py"
# Going to start writing the rest of the book
# Assuming this is true
toplevel_anonymous_class = true
# Not ready
simple_io = false
# Turn on when Java 21 released
java_21 = false

[output.html.playground]
editable = true