[book]
title = "Modern Java"
description = "Book teaching how to write modern and effective Java."
authors = [
    "Ethan McCue",
    "Together Java",
    "Contributions from the Java Community",
]
language = "en"

[output.html]
git-repository-url = "https://github.com/Together-Java/ModernJava"
edit-url-template = "https://github.com/Together-Java/ModernJava/edit/develop/{path}"
mathjax-support = true
additional-css = ["ferris.css"]
additional-js = ["ferris.js"]
heading-split-level = 2

[output.html.fold]
enable = false # whether or not to enable section folding
level = 0      # the depth to start folding

[output.html.playground]
editable = true

[output.html.code.hidelines]
java = "~"
